packages:
  - name: api
    environment:
      VITE_S3_ENDPOINT_URL: ${VITE_S3_ENDPOINT_URL}
      VITE_S3_BUCKET_NAME: ${VITE_S3_BUCKET_NAME}
      S3_REGION: ${S3_REGION}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: production

    functions:
      - name: schema
        runtime: nodejs:18 # Updated runtime
        web: true

      - name: collections
        runtime: nodejs:18 # Updated runtime
        web: true

      - name: auth
        runtime: nodejs:18 # Updated runtime
        web: true
