packages:
  - name: default
    environment:
      VITE_S3_ENDPOINT_URL: ${VITE_S3_ENDPOINT_URL}
      VITE_S3_BUCKET_NAME: ${VITE_S3_BUCKET_NAME}
      S3_REGION: ${S3_REGION}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
    functions:
      # Schema endpoints
      - name: schema
        binary: false
        runtime: nodejs:default
        web: true
        limits:
          timeout: 5000
          memory: 256
        environment:
          NODE_ENV: production
      - name: schema/update
        binary: false
        runtime: nodejs:default
        web: true
        limits:
          timeout: 5000
          memory: 256
        environment:
          NODE_ENV: production

      # Collection endpoints
      - name: collections/update
        binary: false
        runtime: nodejs:default
        web: true
        limits:
          timeout: 5000
          memory: 256
        environment:
          NODE_ENV: production
