environment:
  NODE_ENV: production
  VITE_USE_REMOTE_DATA: ${VITE_USE_REMOTE_DATA}
  VITE_S3_ENDPOINT_URL: ${VITE_S3_ENDPOINT_URL}
  VITE_S3_BUCKET_NAME: ${VITE_S3_BUCKET_NAME}
  S3_REGION: ${S3_REGION}
  S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
  S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
  JWT_SECRET: ${JWT_SECRET}
  ADMIN_USERNAME: ${ADMIN_USERNAME}
  ADMIN_PASSWORD: ${ADMIN_PASSWORD}

packages:
  - name: auth
    functions:
    - name: login
      runtime: nodejs:18
      web: true

  - name: collections
    functions:
    - name: show
      runtime: nodejs:18
      web: true

  - name: schema
    functions:
    - name: show
      runtime: nodejs:18
      web: true

  - name: schema
    functions:
    - name: presigned-url
      runtime: nodejs:18
      web: true

  - name: schema
    functions:
    - name: metadata
      runtime: nodejs:18
      web: true

  - name: schema
    functions:
    - name: make-private
      runtime: nodejs:18
      web: true
